name: Build page

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convertir from Markdown to HTML
      run: pandoc --embed-resources -s README.md -o index.html --metadata title="Conseils de sécurité minecraftiens" --metadata author="idotek"

    - name: Deploy on Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .